// Central export file for all type definitions

// Mirror types
export type {
  MirrorSectionType,
  MirrorSection,
  BrandHealth,
  MarketPosition,
  CompetitorInsight,
  CompetitiveLandscape,
  CurrentAsset,
  CurrentAssets,
  AudienceInsight,
  AudienceProfile,
  Objective,
  ObjectiveMilestone,
  ContentPillar,
  ChannelStrategy,
  BrandStrategy,
  TacticalCampaign,
  ActionTask,
  KPIMetric,
  PerformanceDashboard,
  LearningInsight,
  EnrichmentSchedule,
  IntelligenceOpportunity,
} from './mirror.types';

// Marbs AI Assistant types
export type {
  MarbsMessage,
  MarbsConversation,
  MarbsContext,
  MarbsAction,
  MarbsActionType,
  MarbsSuggestion,
  MarbsCapability,
  MarbsState,
  MarbsRequest,
  MarbsResponse,
  MarbsAnalysisResult,
} from './marbs.types';

// Content types
export type {
  ContentGenerationMode,
  ContentStatus,
  ContentPlatform,
  ContentFormat,
  ContentCalendarItem,
  ContentVariation,
  EngagementMetrics,
  DesignData,
  DesignObject,
  TextData,
  ImageData,
  ShapeData,
  DesignBackground,
  DesignTemplate,
  ContentGenerationRequest,
  ContentGenerationResponse,
  ContentGenerationMetadata,
  SynapseEnrichment,
  SynapseConnection,
  PublishRequest,
  PublishResponse,
  ContentPerformance,
  BenchmarkComparison,
  CalendarView,
  CalendarFilters,
  CalendarEvent,
} from './content.types';

// MARBA Score types
export type {
  MARBAScore,
  MARBABreakdown,
  MessagingScore,
  AuthenticityScore,
  RelevanceScore,
  BrandAlignmentScore,
  ActionScore,
  ComponentScore,
  MARBAInsight,
  MARBAAnalysisContext,
  BrandGuidelines,
  MARBAScoreHistory,
  MARBAScoreSnapshot,
  MARBABenchmark,
  MARBAOptimization,
  OptimizationSuggestion,
  MARBAComparison,
  MARBAABTest,
  ContentPerformanceMetrics,
  RealtimeMARBAScore,
} from './marba-score.types';

// Intelligence types
export type {
  IndustryProfile,
  CustomerTrigger,
  SeasonalityData,
  SeasonalTrend,
  BuyingJourneyStage,
  BenchmarkMetrics,
  SynapseAnalysis,
  Connection,
  PowerWord,
  EmotionalTrigger,
  PersuasionElement,
  OpportunityInsight,
  OpportunityType,
  OpportunitySource,
  SuggestedAction,
  LearningPattern,
  PatternEvidence,
  CompetitiveSnapshot,
  CompetitorMetrics,
  CompetitorContentAnalysis,
  ContentSummary,
  AnalyticsEvent,
  PlatformMetricsSnapshot,
  PlatformMetrics,
  MetricComparisons,
  EngagementInboxItem,
} from './intelligence.types';

// API types
export type {
  APIResponse,
  APIError,
  AnalyzeMirrorRequest,
  AnalyzeMirrorResponse,
  GenerateContentRequest,
  GenerateContentResponse,
  EnrichWithSynapseRequest,
  EnrichWithSynapseResponse,
  PublishToPlatformRequest,
  PublishToPlatformResponse,
  CollectAnalyticsRequest,
  CollectAnalyticsResponse,
  MarbsMessageRequest,
  MarbsMessageResponse,
  CalculateMARBAScoreRequest,
  CalculateMARBAScoreResponse,
  OpenRouterRequest,
  OpenRouterMessage,
  OpenRouterResponse,
  FacebookGraphAPIRequest,
  FacebookGraphAPIResponse,
  LinkedInShareRequest,
  LinkedInShareResponse,
  TwitterTweetRequest,
  TwitterTweetResponse,
  GoogleBusinessPostRequest,
  GoogleBusinessPostResponse,
  EdgeFunctionRequest,
  EdgeFunctionResponse,
  WebhookPayload,
  WebhookResponse,
} from './api.types';
